version: "3.9"

services:
  nginx:
    image: jillyjunggg/sak-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 9999:80
    networks:
      - saksiam

  django:
    image: jillyjunggg/sak-django
    build:
      context: .
      dockerfile: Dockerfile-django
    ports: 
      - 8000:8000
    volumes: 
      - .:/app
    networks:
      - saksiam
    command: /start

networks:
  saksiam:
    external: true
